//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnitHorizon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendIntegrity
    {
        public int Eno { get; set; }
        public System.DateTime CheckFDate { get; set; }
        public System.DateTime CheckTDate { get; set; }
        public string Checked { get; set; }
    }
}
