//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnitHorizon.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Department
    {
        
       
        [Key]
        [Display(Name="Serial No")]
        public int SlNo { get; set; }
        [Display(Name = "Department")]
        public string Department1 { get; set; }
        public string Dept_Desc { get; set; }
    }
}
