//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnitHorizon.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class knithEntities : DbContext
    {
        public knithEntities()
            : base("name=knithEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Advance_Mast> Advance_Mast { get; set; }
        public virtual DbSet<ADVance_Trans> ADVance_Trans { get; set; }
        public virtual DbSet<ATTENDANCE> ATTENDANCEs { get; set; }
        public virtual DbSet<AttendIntegrity> AttendIntegrities { get; set; }
        public virtual DbSet<AttendSummary> AttendSummaries { get; set; }
        public virtual DbSet<Auth_Master> Auth_Master { get; set; }
        public virtual DbSet<BiAnnualReport> BiAnnualReports { get; set; }
        public virtual DbSet<Bonu> Bonus { get; set; }
        public virtual DbSet<BonusLtStmt> BonusLtStmts { get; set; }
        public virtual DbSet<Coff_Requests> Coff_Requests { get; set; }
        public virtual DbSet<Coffs_Trans> Coffs_Trans { get; set; }
        public virtual DbSet<CoffTemp> CoffTemps { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<DailyAttend> DailyAttends { get; set; }
        public virtual DbSet<DaysCount> DaysCounts { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Designation> Designations { get; set; }
        public virtual DbSet<emp_multi_shift> emp_multi_shift { get; set; }
        public virtual DbSet<EmpAttandance> EmpAttandances { get; set; }
        public virtual DbSet<ESIContribution> ESIContributions { get; set; }
        public virtual DbSet<EsiHalfYrCntrbn> EsiHalfYrCntrbns { get; set; }
        public virtual DbSet<EVERYDAY> EVERYDAYs { get; set; }
        public virtual DbSet<ExcessEL> ExcessELs { get; set; }
        public virtual DbSet<Form10> Form10 { get; set; }
        public virtual DbSet<Form2> Form2 { get; set; }
        public virtual DbSet<Form5> Form5 { get; set; }
        public virtual DbSet<FormAR> FormARs { get; set; }
        public virtual DbSet<FormF> FormFs { get; set; }
        public virtual DbSet<FORMR12> FORMR12 { get; set; }
        public virtual DbSet<Grat_Payments> Grat_Payments { get; set; }
        public virtual DbSet<IncentivesStmt> IncentivesStmts { get; set; }
        public virtual DbSet<Increment> Increments { get; set; }
        public virtual DbSet<LEV_MAST> LEV_MAST { get; set; }
        public virtual DbSet<LEV_TRANS> LEV_TRANS { get; set; }
        public virtual DbSet<LicStatu> LicStatus { get; set; }
        public virtual DbSet<PAYREG> PAYREGs { get; set; }
        public virtual DbSet<PAYREGC> PAYREGCs { get; set; }
        public virtual DbSet<PERMISSION> PERMISSIONs { get; set; }
        public virtual DbSet<PERMISSION1> PERMISSIONS1 { get; set; }
        public virtual DbSet<PFContribution> PFContributions { get; set; }
        public virtual DbSet<PFSummary> PFSummaries { get; set; }
        public virtual DbSet<ProvidentFund> ProvidentFunds { get; set; }
        public virtual DbSet<PTaxReturn> PTaxReturns { get; set; }
        public virtual DbSet<Qualification> Qualifications { get; set; }
        public virtual DbSet<QuarterReport> QuarterReports { get; set; }
        public virtual DbSet<RANx> RANGES { get; set; }
        public virtual DbSet<Reminder> Reminders { get; set; }
        public virtual DbSet<ReminderStatu> ReminderStatus { get; set; }
        public virtual DbSet<RepAttend> RepAttends { get; set; }
        public virtual DbSet<RepAttendance> RepAttendances { get; set; }
        public virtual DbSet<RepCoff> RepCoffs { get; set; }
        public virtual DbSet<RepGrat> RepGrats { get; set; }
        public virtual DbSet<RepSecurity> RepSecurities { get; set; }
        public virtual DbSet<SecPunch> SecPunches { get; set; }
        public virtual DbSet<SHIFT_MASTER> SHIFT_MASTER { get; set; }
        public virtual DbSet<tblbuyer> tblbuyers { get; set; }
        public virtual DbSet<tblpaycode> tblpaycodes { get; set; }
        public virtual DbSet<TempAttend> TempAttends { get; set; }
        public virtual DbSet<TempDailyAttend> TempDailyAttends { get; set; }
        public virtual DbSet<TempEsiHalfYr> TempEsiHalfYrs { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<UType_Master> UType_Master { get; set; }
        public virtual DbSet<attnupdate_log> attnupdate_log { get; set; }
        public virtual DbSet<COFFREQMAY> COFFREQMAYs { get; set; }
        public virtual DbSet<EMP> EMPs { get; set; }
        public virtual DbSet<empyrsalreport> empyrsalreports { get; set; }
        public virtual DbSet<EsiHalfYrTemp> EsiHalfYrTemps { get; set; }
        public virtual DbSet<FORMR1> FORMR1 { get; set; }
        public virtual DbSet<FORMR11> FORMR11 { get; set; }
        public virtual DbSet<FURTIVE> FURTIVEs { get; set; }
        public virtual DbSet<LEV_MAST1> LEV_MAST1 { get; set; }
        public virtual DbSet<Payreg1> Payreg1 { get; set; }
        public virtual DbSet<PfYearContribution> PfYearContributions { get; set; }
        public virtual DbSet<RPTATTEND> RPTATTENDs { get; set; }
        public virtual DbSet<RPTESI> RPTESIs { get; set; }
        public virtual DbSet<RPTOT> RPTOTs { get; set; }
        public virtual DbSet<RULE> RULES { get; set; }
        public virtual DbSet<rupayan> rupayans { get; set; }
        public virtual DbSet<SHIFTB> SHIFTBs { get; set; }
        public virtual DbSet<tbl_sl> tbl_sl { get; set; }
        public virtual DbSet<tbl_style> tbl_style { get; set; }
        public virtual DbSet<tblBonusRange> tblBonusRanges { get; set; }
        public virtual DbSet<tblextrapaycode> tblextrapaycodes { get; set; }
        public virtual DbSet<tblStylePart> tblStyleParts { get; set; }
        public virtual DbSet<tblStyleRate> tblStyleRates { get; set; }
        public virtual DbSet<temppayreg> temppayregs { get; set; }
        public virtual DbSet<tempyrsal> tempyrsals { get; set; }
    }
}
